version: '3.4'

services:
  postgres:
    image:  postgres:13-alpine
    networks: [ app ]
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - "5444:5432"

networks:
  app:
