version: '3.4'

services:
  postgres:
    image: postgres:13-alpine
    networks: [ app ]
    env_file:
      - .env
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    networks: [ app ]
    env_file:
      - .env
    volumes:
      - ./database/migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB?sslmode=disable", "up" ]
    links:
      - postgres
    depends_on:
      - postgres

  app:
    build: .
    restart: always
    networks: [ app ]
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - .env
    volumes:
      - ./log:/log
networks:
  app:
